accounts/urls.py
from django.conf.urls import url
from . import views
from accounts.forms import CustomAuthForm
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy

app_name = 'accounts'

urlpatterns = [




    url(r'^signup/$', views.SignUpView, name='signup'),
    url(r'^signup/profile/$', views.ProfileView, name='profile'),
    url(r'^login/$', auth_views.login, name='login', kwargs={"authentication_form": CustomAuthForm}),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^terms/condition/$', views.terms, name='tc'),
    url(r'^privacy_policy/$', views.privacy, name='privacy'),
    url(r'^copyright/$', views.copyright_policy, name='copyright'),

    # ---------------------------------------PASSWORD CHANGE-----------------------------------------------------------

    url(r'^password-change/$', auth_views.password_change, {'template_name': 'registration/password_change_form.html',
                                                            'post_change_redirect': 'registration/password_change_done/'},
        name='password_change'),

    url(r'^password-change/registration/password_change_done/$', auth_views.password_change_done,
        {'template_name': 'registration/password_change_done.html'}, name='password_change_done'),

    # ----------------------------------------PASSWORD RESET------------------------------------------------------------

    url(r'password-reset/$', PasswordResetView.as_view(template_name='accounts/password_reset_form.html',
                                                       success_url=reverse_lazy('accounts:password_reset_done'),
                                                       email_template_name='accounts/password_reset_email.html',
                                                       subject_template_name='accounts/password_reset_subject.txt'),
        name='password_reset'),

    url(r'password-reset/done/$', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),

    url(r'reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
                                         success_url=reverse_lazy('accounts:password_reset_complete')),
        name="password_reset_confirm"),

    url(r'^reset/complete/$', PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name="password_reset_complete"),

]

food/urls.py
from django.conf.urls import url
from . import views
from django.urls import path


app_name = 'food'

urlpatterns = [


    url(r'restaurants$', views.restaurants_list_view, name='restaurants_list'),
    url(r'restaurants/advanced$', views.advanced_search_view, name='advanced_list'),
    url(r'^restaurants/my$', views.my_restaurant_list, name='my_restaurant_list'),
    url(r'^restaurants/(?P<pk>[0-9]+)/$', views.restaurant_detail_view, name='restaurant-detail'),
    url(r'^menu/(?P<pk>[0-9]+)/add/$', views.add_to_cart,name='add-cart'),
    url(r'^cart/$', views.cart_view, name='my_cart'),
    url(r'^cart/(?P<pk>[0-9]+)/delete/$', views.delete_from_cart, name='delete-cart'),
    url(r'^order/confirm/$', views.order_confirm_view, name='order_confirm'),
    url(r'^clear/cart/$', views.clear_cart, name='delete-all-cart'),
    url(r'^contact/$', views.contact_view, name='contact'),
    url(r'^my-orders/$', views.my_orders_view, name='my_orders'),
    url(r'^my-orders/(?P<pk>[0-9]+)/$', views.my_order_deatil, name='my_orders_detail'),
    url(r'^cart/order/paypal/confirm/$', views.paypal_cnf, name='paypal_cnf'),



]

hunger/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^food/', include('food.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^ordermanage/', include('ordermanage.urls')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ordermanage/urls.py
from django.conf.urls import url
from . import views
from django.urls import path


app_name = 'ordermanage'

urlpatterns = [


    url(r'^orders/$', views.order_list_view, name='order-list'),
    url(r'orders/(?P<pk>[0-9]+)/detail/$', views.order_detail_view, name='order-detail'),
    url(r'orders/(?P<pk>[0-9]+)/confirm/$',views.order_list_update_view, name='order-list-update'),
    url(r'confirm-orders/$', views.confirm_orders, name='order-confirm-list'),
    url(r'confirm-orders/(?P<pk>[0-9]+)/$', views.confirm_order_detail, name='confirm-order'),
    url(r'restaurants/orders/$', views.resturants_orders, name='order'),






]

ordermanage/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from food.models import Menu,CartManager


class OrdersDone(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None, blank=True, null=True)
    item = models.ForeignKey(Menu, on_delete=models.CASCADE, null=True)
    cartmanager = models.ForeignKey(CartManager, on_delete=models.CASCADE, null=True)
    add_time = models.DateTimeField(auto_now=True)
    item_price = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    etc_price = models.DecimalField(max_digits=6, decimal_places=2, default=0)

    def __str__(self):
        return str(self.item)


class OrderManager(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None, blank=True, null=True)
    delivery_time = models.DateTimeField(auto_now_add=True)
    order_id = models.CharField(max_length=10, default=0)
    payment = models.CharField(max_length=20,  )
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    sub_total = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    status = models.BooleanField(default=False)
    etc_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return str(self.order_id)


class OrdersConfirm(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None, blank=True, null=True)
    item = models.ForeignKey(Menu, on_delete=models.CASCADE, null=True)
    cartmanager = models.ForeignKey(OrderManager, on_delete=models.CASCADE, null=True)
    add_time = models.DateTimeField(auto_now=True)
    item_price = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    etc_price = models.DecimalField(max_digits=6, decimal_places=2, default=0)

    def __str__(self):
        return str(self.item)

food/forms.py
from django import forms
from food.models import Cart


class CartForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields= ['user','item']

food/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from food.models import Restaurant, Menu, Cart
from django.conf import settings
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse
from django.contrib.auth.decorators import login_required
from food.forms import CartForm
from django.core.exceptions import ObjectDoesNotExist
from food.models import CartManager
from ordermanage.models import OrdersDone, OrderManager
from twilio.rest import Client
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from accounts.forms import ContactUsForm
from paypal.standard.forms import PayPalPaymentsForm


def home(request):
    my_cart = Cart.objects.filter(user=request.user)
    return render(request, 'food/base.html', {'my_cart':my_cart})


def restaurants_list_view(request):

    if request.method == "POST":
        search = request.POST['search']
        queryset_list = Restaurant.objects.filter(name__icontains=search).order_by("name") or \
                        Restaurant.objects.filter(address__icontains=search).order_by("name") or\
                        Restaurant.objects.filter(category__icontains=search).order_by("name")

        paginator = Paginator(queryset_list, 4)
        page = request.GET.get('page')
        queryset_list = paginator.get_page(page)

        context = {
            'restaurants_list': queryset_list,
            'page': search,

        }
        return render(request, "food/searched_restaurants.html", context)

    else:

        if request.user.is_authenticated:
            queryset_list = Restaurant.objects.all().order_by("name") and Restaurant.objects.all().order_by("-rating")
            paginator = Paginator(queryset_list, 4)
            page = request.GET.get('page')
            queryset_list = paginator.get_page(page)

            area = request.user.profile.area
            queryset_list_mine = Restaurant.objects.filter(area=area).order_by("name")

            paginator_mine = Paginator(queryset_list_mine, 4)
            page_mine = request.GET.get('page')
            queryset_list_mine = paginator_mine.get_page(page_mine)

            my_cart = Cart.objects.filter(user=request.user)
            all_list = Restaurant.objects.all()
            contact = ContactUsForm
            context = {'restaurants_list': queryset_list,
                       'mine_restaurant_list': queryset_list_mine,
                       'my_cart':my_cart,
                       'all_list': all_list,
                       'form':contact
                       }

            return render(request, "food/restaurants_list.html", context)

        else:
            queryset_list = Restaurant.objects.all().order_by("name") and Restaurant.objects.all().order_by("-rating")
            paginator = Paginator(queryset_list, 4)
            page = request.GET.get('page')
            queryset_list = paginator.get_page(page)
            all_list = Restaurant.objects.all()
            contact = ContactUsForm
            context = {
                'restaurants_list': queryset_list,
                'all_list': all_list,
                'form': contact
            }

            return render(request, "food/restaurants_list.html", context)


def advanced_search_view(request):
    if request.method == 'POST':
        category = request.POST['optradio']
        area = request.POST['area']
        queryset_list1 = Restaurant.objects.filter(category__icontains =category, area__icontains=area)

        paginator_mine = Paginator(queryset_list1, 4)
        page_mine = request.GET.get('page')
        queryset_list1 = paginator_mine.get_page(page_mine)

        context = {'restaurant_list1': queryset_list1,

        }
        return render(request, "food/advanced_search.html", context)


def my_restaurant_list(request):
    if request.method == 'POST':
        search = request.POST['search']
        area = request.user.profile.area

        queryset_list_mine = Restaurant.objects.filter(name__icontains=search, area=area).order_by("name")

        paginator_mine = Paginator(queryset_list_mine, 4)
        page_mine = request.GET.get('page')
        queryset_list_mine = paginator_mine.get_page(page_mine)
        context = {
                   'mine_restaurant_list': queryset_list_mine,
                    'page': search,
        }
        return render(request, "food/my_restaurants_list.html", context)
    else:
        return redirect('/food/restaurants')


def restaurant_detail_view(request, pk):
    restaurant_instance = get_object_or_404(Restaurant, pk=pk)
    return render(request, 'food/restaurant_detail.html', {'restaurant': restaurant_instance})


@login_required
def add_to_cart(request, pk):
    menu = get_object_or_404(Menu, pk=pk)
    if request.method == "POST":
        etc_cost = request.POST.get("cost", None)
        cart = Cart()
        cart.user = request.user
        cart.item = menu
        cart.item_price = menu.price
        cart.etc_price = etc_cost
        cart.save()

        return JsonResponse({'user': cart.user.username})

    else:
        return HttpResponse("request Must be post")


@login_required
def cart_view(request):

        query_set = Cart.objects.filter(user=request.user)
        cart_count = Cart.objects.filter(user=request.user).count()
        context = {
            'cart_list': query_set,
            'cart_count':cart_count,
        }
        return render(request, 'food/cart.html', context)


@login_required
def delete_from_cart(request, pk):
    item = get_object_or_404(Cart, pk=pk)
    item.delete()
    messages.success(request, "Item Removed From Cart")
    return redirect('/food/cart/')


@login_required
def order_confirm_view(request):
    if request.method == 'POST':
        order_no = request.POST['order']
        payment = request.POST['payment']
        total = request.POST['total_amount']
        etc = request.POST['etc_amount']
        sub_total = request.POST['sub_total_amount']

        checkout = CartManager()
        checkout.order_id = order_no
        checkout.user = request.user
        checkout.sub_total = sub_total
        checkout.payment = payment
        checkout.etc_price = etc
        checkout.total = total

        checkout.save()

        for order in Cart.objects.filter(user=request.user):
            order_done = OrdersDone()
            order_done.user = order.user
            order_done.item = order.item
            order_done.cartmanager = checkout
            order_done.item_price = order.item_price
            order_done.etc_price = order.etc_price
            order.cartmanager = checkout
            order.save()

            order_done.save()
        Cart.objects.filter(user=request.user).delete()

        context = {
            'order_no': order_no,
            'total': sub_total
        }
        account_sid = "ACfcdc76a71768bba5a8fa1695dece27c9"
        auth_token = "f6683c048cee22a89dcf20e4009caca8"

        client = Client(account_sid, auth_token)
        number = request.user.profile.phone
        num = "+91"+number
        # client.api.account.messages.create(to=num, from_="+18305005658", body="Hello"+request.user.first_name+"!!"+
        # "Your order has placed Successfully under"
        # "the order number"+order_no+" ."+"You"

        # " need to pay"+total+".")

        if payment == 'COD':
            return render(request, 'food/confirm_order.html', context)

        elif payment == 'Paytm':
            return render(request, 'food/paypal_order.html', context)

        else:
            x = int(order_no)
            paypal_dict = {
                "business": settings.PAYPAL_RECEIVER_EMAIL,
                "amount": sub_total,
                "item_name": x,
                "invoice": x,
                #"notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
                "return": request.build_absolute_uri(reverse('food:paypal_cnf')),
                "cancel_return": request.build_absolute_uri(reverse('food:paypal_not_cnf')),
                # "custom": "premium_plan",

            }
            form = PayPalPaymentsForm(initial=paypal_dict)
            context = {"form": form}
            return render(request, "food/paypal_order.html", context)

    else:
        return redirect('/food/restaurants')


@login_required
def paypal_cnf(request):
    if request.method == 'GET':
        if CartManager.objects.exists():
            my_order = CartManager.objects.filter(payment = "credit/debit").order_by("-order_time")[0:1] and CartManager.objects.filter(user =request.user).order_by("-order_time")[0:1]
            return render(request, 'food/cnf_paypal.html', {'order': my_order})


@login_required
def clear_cart(request):
    if request.method == 'POST':
        Cart.objects.filter(user=request.user).delete()
        return redirect('/food/cart/')
    else:
        return redirect('/food/cart/')


@login_required
def cart(request):
    query = Cart.objects.filter(user=request.user)
    return render(request,'food/base.html',{'list':query})


def contact_view(request):
    if request.method == 'POST':
        contact = ContactUsForm(request.POST)
        if contact.is_valid():
            con = contact.save(commit=False)
            con.user = request.user
            con.save()
            messages.success(request, "Your Feedback has been submitted")
            return redirect('/food/restaurants')
        else:
            return redirect('/food/restaurants/')
    else:
        return redirect('/food/restaurants')

@login_required
def my_orders_view(request):
    orders = OrderManager.objects.filter(user= request.user).order_by("-delivery_time")
    return render(request,'food/my_orders.html',{'all_orders':orders})

@login_required
def my_order_deatil(request,pk):
    order = get_object_or_404(OrderManager,pk=pk)

food/templates/food/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
      <link href='https://fonts.googleapis.com/css?family=Amita' rel='stylesheet'>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
      <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false&libraries=places"></script>
      {%load staticfiles %}
      <link rel="stylesheet" type="text/css" href="{% static 'food/base.css'%}">
       <link rel="icon" type="img/ico" href="https://pi360.net/site/images/favicon.ico">
        <title>

      {% block title%}

      {% endblock %}
            </title>

<style>


 @import url("https://fonts.googleapis.com/css?family=Amatic+SC");
body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
.w3-bar-block .w3-bar-item {padding:20px}

#h{
  width: 100%;
  text-align: center;
  font-family: 'Amatic SC';
  color: #333;
  opacity: 1;

  background-color:#FFD454;
  height:1600px;

  Z-index:99999;
}
#t{
  font-size: 140px;
 margin-top:100px;
  Z-index:1;
 animation:pulse 2.5s linear infinite;

}
@keyframes pulse {
  0% {
    transform: scale(1, 1);
    opacity: .25;
  }
  50% {
    transform: scale(1.2, 1);
    opacity: 1;
  }
  100% {
    transform: scale(1, 1);
    opacity: .25;
  }
}

.loader {
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #2f2f2f;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite; /* Safari */
  animation: spin 2s linear infinite;
}

/* Safari */
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}


</style>
    </head>

<body onload="get_rout();">

<div class="navbar navbar-fixed-top" id="h">
<p id="t" align="center"> Loading in progress..</p>
    <div align="center">
        <div class="loader"></div>
    </div>
</div>

<!-- Nav bar menu -->

 <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a id="heading1"  class="navbar-brand" href="{%url 'food:restaurants_list'%}">24x7 HUNGER</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
          <li><a id="menu1" href="#about"  ><span class="glyphicon glyphicon-globe"></span>&nbsp;About</a></li>
        <li><a id="menu2" href="#contact"><span class="glyphicon glyphicon-envelope"></span> &nbsp;Contact Us</a></li>
          <li> <a id="menu7" data-toggle="modal" data-target="#myModal">   <span class="glyphicon glyphicon-filter"></span>&nbsp;Filter Search</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          {%if request.user.is_authenticated%}
          <li><a id="menu3" class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user"></span>&nbsp;Hello {{request.user.username}}<span class="caret"></span></a>

                <ul class="dropdown-menu">
                     {%if user.is_superuser or user.is_staff%}
                    <li><a href="{%url 'ordermanage:order-list'%}"  id="menu5"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;view orders</a></li>
                        {%endif%}
                      {%if user.is_superuser %}
                    <li><a href="/ordermanage/restaurants/orders/"  id="menu5"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;Restaurants Payments</a></li>
                    {%endif%}
                    <li><a class="menu1" href="{%url 'accounts:profile'%}"><span class="glyphicon glyphicon-user"></span>&nbsp;Edit My Profile</a></li>
                     <li><a class="menu1" href="{%url 'accounts:password_change'%}"><span class="glyphicon glyphicon-edit"></span>&nbsp;Change Password</a></li>
                  <li><a class="menu1" href="{%url 'food:my_orders'%}"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;My Orders</a></li>
                  <li><a class="menu1" href="{%url 'accounts:logout'%}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;Logout</a></li>
                </ul></li>


          <li><a id="menu4" href="{%url 'food:my_cart'%}"><span class="glyphicon glyphicon-shopping-cart"></span>&nbsp;My Cart<span class="badge"></span> </a></li>
          {%else%}
        <li><a id="menu8" href="{%url 'accounts:signup'%}"><span class="glyphicon glyphicon-user"></span>&nbsp;SignUp</a></li>
        <li><a id="menu6" href="{%url 'accounts:login'%}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;Login</a></li>
          {%endif%}
      </ul>
    </div>
  </div>
</nav>

 <!--Filter Modal -->

  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
            <h2 align="center" class="modal-title" style="color:rgb(255,127,80);"><b>Welcome to 24x7 Advance search</b></h2>
        </div>


        <div class="modal-body">
            <form method="post" action="/food/restaurants/advanced" enctype="multipart/form-data">
                {%csrf_token%}

          <h3 align="center">Please Choose Category:</h3>
            <p><b><u>You are looking for:</u></b></p>
             <div class="radio">
              <label><input type="radio" value="fast" name="optradio"  required>Fast Food</label>
            </div>
            <div class="radio">
              <label><input type="radio" value="destination" name="optradio">Destination Restaurant</label>
            </div>
            <div class="radio disabled">
              <label><input type="radio" value="cafe" name="optradio"  >Cafe</label>
            </div>
                 <div class="radio disabled">
              <label><input type="radio" value="street" name="optradio"  >Street Food</label>
            </div>
             <div class="radio disabled">
              <label><input type="radio" value="dhaba" name="optradio" >Dhaba</label>
            </div>



             <h3 align="center">Please Choose Area:</h3>
            <p><b><u>You are looking Food Destination at:</u></b></p>

             <div class="form-group">
              <label for="sel1">Select Area:</label>
              <select name="area" class="form-control" id="sel1">

                  <option value="janipur">janipur</option>
                <option value="disco road">Disco Road</option>
                <option value="talli morh">Talli Morh</option>
                  <option value="New Plot">New Plot</option>
                <option value="amphalla">Amphalla</option>
                <option value="rehari">Rehari</option>
            </select>
             </div>
                <button class="btn btn-info btn-block">Submit</button>
                </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

 {%block body%}
 {%endblock%}

<hr>
  <footer>
       <div class="navbar navbar-default">
           <div class="container-fluid">

       <div class="w3-container w3-padding-32 w3-center">

            <ul class="list-inline social-buttons">
                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>

    <div class="w3-padding-25">

      <h4><b>Disclaimer</b></h4>
      <h6><i>The information contained on <b>www.247Hunger.com</b>  is provided for informational purposes
          only and is not meant  to substitute for the advice provided by your doctor or other healthcare
          professional. </i></h6>

  </div>

            <div class="row">
                <hr>
                <div class="col-md-4">
                  <span class="copyright">Designed by <b><a href="https://www.facebook.com/settings?tab=account&section=advertising_email">Arun Sharma</a></b> </span>
                </div>
                <div class="col-md-2">

                </div>
                <div class="col-md-8">
                    <ul class="list-inline quicklinks">
                        <li><a href="{%url 'accounts:copyright'%}"><b>Copyright Policy</b></a>
                        </li>
                        <li><a href="{%url 'accounts:tc'%}"><b>Terms and Conditions</b></a>
                        </li>
                        <li><a href="{%url 'accounts:privacy'%}"><b>Privacy Policy</b></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
      </div>
       </div>
  </footer>

<script>
// Script to open and close sidebar
function w3_open() {
    document.getElementById("mySidebar").style.display = "block";
}

function w3_close() {
    document.getElementById("mySidebar").style.display = "none";
}


$(document).ready(function(){
  // Add smooth scrolling to all links
  $("a").on('click', function(event) {

    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {
      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;


      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 800, function(){

        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
});

function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else {
        x.innerHTML = "Geolocation is not supported by this browser.";
    }
}

jQuery(window).load(function(){
    jQuery("#h").fadeOut(1000);

        });
    </script>
</body>
</html>

food/templates/food/cnf_paypal.html
{%extends 'food/base.html'%}
{%block body%}

<div class="container" style="margin-top:130px">
    <div class="row">

        <div class="jumbotron col-sm-12">
            <h1 align="center" style="font-size:90px;"><span class="glyphicon glyphicon-ok-sign"></span></h1>
            <h2 align="center">Your Order is placed Successfully</h2>
            {%for order in order%}
            <h3 align="center">Your Order number:&nbsp;<b>{{order.order_id}}</b></h3>
            <h4 align="center">You have Paid:&nbsp;<b><span class="fa fa-inr"></span>&nbsp;{{order.sub_total}}</b></h4>
            {%endfor%}
            <br>     <br>
        </div>
    </div>

</div>
<script>
    $(window).on('beforeunload', function() {
  $(window).on('unload', function() {
    window.location.href = '/food/restaurants';
  });

  return 'Not an empty string';
});


</script>
{%endblock%}

food/templates/food/paypal_order.html
{%extends 'food/base.html'%}
{%block body%}

<div class="container" style="margin-top:70px">
    <div class="row">



 {{ form.render }}



    </div>
</div>

{%endblock%}