accounts/urls.py
from django.conf.urls import url
from . import views
from accounts.forms import CustomAuthForm
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy

app_name = 'accounts'

urlpatterns = [




    url(r'^signup/$', views.SignUpView, name='signup'),
    url(r'^signup/profile/$', views.ProfileView, name='profile'),
    url(r'^login/$', auth_views.login, name='login', kwargs={"authentication_form": CustomAuthForm}),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^terms/condition/$', views.terms, name='tc'),
    url(r'^privacy_policy/$', views.privacy, name='privacy'),
    url(r'^copyright/$', views.copyright_policy, name='copyright'),

    # ---------------------------------------PASSWORD CHANGE-----------------------------------------------------------

    url(r'^password-change/$', auth_views.password_change, {'template_name': 'registration/password_change_form.html',
                                                            'post_change_redirect': 'registration/password_change_done/'},
        name='password_change'),

    url(r'^password-change/registration/password_change_done/$', auth_views.password_change_done,
        {'template_name': 'registration/password_change_done.html'}, name='password_change_done'),

    # ----------------------------------------PASSWORD RESET------------------------------------------------------------

    url(r'password-reset/$', PasswordResetView.as_view(template_name='accounts/password_reset_form.html',
                                                       success_url=reverse_lazy('accounts:password_reset_done'),
                                                       email_template_name='accounts/password_reset_email.html',
                                                       subject_template_name='accounts/password_reset_subject.txt'),
        name='password_reset'),

    url(r'password-reset/done/$', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),

    url(r'reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
                                         success_url=reverse_lazy('accounts:password_reset_complete')),
        name="password_reset_confirm"),

    url(r'^reset/complete/$', PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name="password_reset_complete"),

]

food/urls.py
from django.conf.urls import url
from . import views
from django.urls import path


app_name = 'food'

urlpatterns = [


    url(r'restaurants$', views.restaurants_list_view, name='restaurants_list'),
    url(r'restaurants/advanced$', views.advanced_search_view, name='advanced_list'),
    url(r'^restaurants/my$', views.my_restaurant_list, name='my_restaurant_list'),
    url(r'^restaurants/(?P<pk>[0-9]+)/$', views.restaurant_detail_view, name='restaurant-detail'),
    url(r'^menu/(?P<pk>[0-9]+)/add/$', views.add_to_cart,name='add-cart'),
    url(r'^cart/$', views.cart_view, name='my_cart'),
    url(r'^cart/(?P<pk>[0-9]+)/delete/$', views.delete_from_cart, name='delete-cart'),
    url(r'^order/confirm/$', views.order_confirm_view, name='order_confirm'),
    url(r'^clear/cart/$', views.clear_cart, name='delete-all-cart'),
    url(r'^contact/$', views.contact_view, name='contact'),
    url(r'^my-orders/$', views.my_orders_view, name='my_orders'),
    url(r'^my-orders/(?P<pk>[0-9]+)/$', views.my_order_deatil, name='my_orders_detail'),
    url(r'^cart/order/paypal/confirm/$', views.paypal_cnf, name='paypal_cnf'),



]

hunger/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^food/', include('food.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^ordermanage/', include('ordermanage.urls')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User


Area_Choice = (
    ('janipur', 'janipur'),
    ('disco road', 'disco road'),
    ('Talli morh', 'Talli morh'),
    ('New Plot', 'New Plot'),
    ('Ptoli', 'Ptoli'),
    ('Lower Roop Nagar', 'Lower Roop Nagar'),
    ('upper roop Nagar', 'Upper Roop Nagar'),
    ('Old Janipur', 'Old janipur'),
    ('gandhinagar','GandhiNagar'),
    ('Trikuta Nagar','Trikuta Nagar'),
    ('Amphalaa','Amphalla'),
    ('rehari','Rehari'),
)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,unique=True,primary_key=True, on_delete=models.CASCADE)
    phone = models.CharField(max_length=10, blank=False)
    area = models.CharField(max_length=20, choices=Area_Choice, default='None')
    address = models.CharField(max_length=40, blank=False)
    pincode = models.CharField(max_length=6, blank=False)
    land_mark = models.CharField(max_length=30, blank=False)
    tc = models.BooleanField(blank=False, default=False)
    longitude = models.FloatField(max_length=30,null=True)
    latitude = models.FloatField(max_length=30, null=True)

    def __str__(self):
        return str(self.user)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class ContactUs(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=40, blank=False)
    phone = models.CharField(max_length=10, blank=False)
    email = models.EmailField(max_length=40, blank=False)
    Comment_and_Suggestion = models.TextField(max_length=1000, blank=False)

    def __str__(self):
        return str(self.user)

accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from accounts.models import Profile
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.utils.translation import gettext as _
from django.contrib.auth.forms import AuthenticationForm

from django.forms.widgets import PasswordInput, TextInput
from accounts.models import ContactUs


class CustomAuthForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control','id':'myInput'}))


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=20, label='First Name')
    last_name = forms.CharField(max_length=20)
    email = forms.EmailField(max_length=60, label='Email Address',)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2',]

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.\
            update({

            'class': 'form-control',
            'id':'form',

        })
        self.fields['password1'].widget.attrs. \
            update({

            'class':'form-control',
            'name':'pass'

        })
        self.fields['username'].widget.attrs. \
            update({

            'class': 'form-control',


        })

        self.fields['password2'].widget.attrs. \
            update({

            'class': 'form-control',

        })
        self.fields['first_name'].widget.attrs. \
            update({

            'class': 'form-control',

        })
        self.fields['last_name'].widget.attrs. \
            update({

            'class': 'form-control',

        })


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['phone'].widget.attrs. \
            update({

            'class': 'form-control',
            'id':'phone',



        })
        self.fields['address'].widget.attrs. \
            update({

            'class': 'form-control',

        })
        self.fields['pincode'].widget.attrs. \
            update({

            'class': 'form-control',




        })
        self.fields['area'].widget.attrs. \
            update({

            'class': 'form-control',

        })
        self.fields['land_mark'].widget.attrs. \
            update({

            'class': 'form-control',

        })
        self.fields['tc'].widget.attrs. \
            update({

            'required':'true',

        })




class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        exclude = ['user']


    def __init__( self, *args, **kwargs):
        super(ContactUsForm, self).__init__(*args, **kwargs)
        self.fields['phone'].widget.attrs. \
            update({

            'class': 'form-control',
            'id':'phone',




        })
        self.fields['email'].widget.attrs. \
            update({

            'class': 'form-control',

        })
        self.fields['name'].widget.attrs. \
            update({

            'class': 'form-control',




        })
        self.fields['Comment_and_Suggestion'].widget.attrs. \
            update({

            'class': 'form-control',




        })


class SignUpEditForm(forms.ModelForm):
    username = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=20, label='First Name')
    last_name = forms.CharField(max_length=20)
    email = forms.EmailField(max_length=60, label='Email Address',)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

    def __init__(self, *args, **kwargs):
        super(SignUpEditForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.\
            update({

            'class': 'form-control',
            'id':'form',

        })

        self.fields['username'].widget.attrs. \
            update({

            'class': 'form-control',


        })


        self.fields['first_name'].widget.attrs. \
            update({

            'class': 'form-control',

        })
        self.fields['last_name'].widget.attrs. \
            update({

            'class': 'form-control',

        })

accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.forms import SignUpForm, ProfileForm,SignUpEditForm
from django.contrib import messages
from django.contrib.auth.admin import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from accounts.models import Profile
from django.contrib.auth.views import login
from django.core.mail import send_mail
from django.conf import settings

#Eamil
subject = 'Account Created Successfully.'
message = 'Welcome To 24/7 Hunger Your ./n' \
          'Now You can order Food from any Restaurants./n' \
          'Just Visit the website and start Ordering.'


def SignUpView(request):
    template_name = 'accounts/index.html'

    if request.method == 'POST':
        form = SignUpForm(request.POST, request.FILES)
        if form.is_valid():
            form1 = form.save(commit=False)
            email = form.cleaned_data['email']
            if email and User.objects.filter(email=email).exists():
                messages.success(request, "Email address"+" "+email+" "+"Already Registered.")
                return render(request, template_name, {'form': form})
            form1.save()
            from_email = settings.EMAIL_HOST_USER
            to_list = [email]
            send_mail(subject, message, from_email, to_list, fail_silently=True)
            messages.success(request, "Your account has been created Successfully")
            return redirect('accounts:profile')
        return render(request,template_name, {'form': form})
    else:
        form = SignUpForm
        return render(request, template_name, {'form': form})


@login_required
def ProfileView(request):
    template_name = 'accounts/Profile_form.html'

    if request.method == 'POST':
        form = SignUpEditForm(request.POST, instance=request.user)
        form1 = ProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if form.is_valid() and form1.is_valid():
            profile = form1.save(commit=False)
            user = form.save(commit=False)
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            phone = form1.cleaned_data['phone']
            if email and User.objects.filter(email=email).exclude(username=username).exists():
                messages.success(request, "Email address"+" "+email+" "+"Already Registered.")
                return render(request, template_name, {'form': form1, 'form1': form})

            elif phone and Profile.objects.filter(phone=phone).exclude(user=request.user).exists():
                messages.success(request, "Phone Number" + " " + phone + " " + "Already Registered.")
                return render(request, template_name, {'form': form1, 'form1': form})

            profile.save()
            user.save()
            messages.success(request, "Your Profile Updated Successfully.")
            return redirect('food:restaurants_list')
        return render(request, template_name, {'form': form1, 'form1': form})

    else:
        form = SignUpEditForm(instance=request.user or None)
        form1 = ProfileForm(instance=request.user.profile or None)
        context ={
            'form': form1,
            'form1': form
        }

        return render(request, template_name, context)



def copyright_policy(request):
    return render(request,'accounts/copyright.html', {})


def terms(request):
    return render(request, 'accounts/terms.html', {})


def privacy(request):
    return render(request, 'accounts/privacy.html', {})

accounts/templates/accounts/Profile_form.html
{%extends 'food/base.html'%}

{%block body%}

<br><br><br><br>

		<div class="container">
	{%if messages%}

        {%for message in messages%}
    <div align="center" class="alert alert-danger" id="msg">
        <strong>{{message}}</strong>
    </div>
        {%endfor%}
    {%endif%}

	    <strong id="err"></strong>
	  {%if form1.errors%}
	 <div align="center" class="alert alert-danger">
        <strong>{{ form1.username.errors }}</strong>
    </div>
			 
	{%endif%}


				<div class="row">

	<div class="col-sm-4"></div>

	<div class="well well-lg col-sm-4"  style="margin-left:10px;">

				{%if request.user.profile.tc%}

					<h2 id="head"  align="center">
						Edit Your Profile
					 </h2><br />
				{%else%}
					<h2 id="head"  align="center">
						Complete Your Profile
					 </h2><br />

				{%endif%}

				<form   class="form-horizontal" action="" method="post" enctype="multipart/form-data">
					  {% csrf_token %}
					 <div class="form-group">
							 {{form1.username.label_tag}}
							{{form1.username}}

						 </div>

					 <div class="form-group">
							 {{form1.email.label_tag}}
							{{form1.email}}

						 </div>
					 <div class="form-group">
							 {{form1.first_name.label_tag}}
							{{form1.first_name}}

						 </div>

					 <div class="form-group">
							 {{form1.last_name.label_tag}}
							{{form1.last_name}}

						 </div>





						 <div class="form-group">
							 {{form.area.label_tag}}
							{{form.area}}

						 </div>

					 <div class="form-group">
							 {{form.address.label_tag}}
							{{form.address}}

						 </div>


					 <div class="form-group">
							 {{form.phone.label_tag}}
							{{form.phone}}

						 </div>


					 <div class="form-group">
							 {{form.pincode.label_tag}}
							{{form.pincode}}

						  <input type="hidden" name="latitude" step="any" required id="id_latitude" />
						  <input type="hidden" name="longitude" step="any" required id="id_longitude" />


						 </div>


					 <div class="form-group">
							 {{form.land_mark.label_tag}}
							{{form.land_mark}}

						 </div>


					 <div class="checkbox">

						 &nbsp; &nbsp; &nbsp;{{form.tc}} You are agree with all the <b><a>Terms and Conditions</a></b>

						 </div>

					<br>
					<br>
					<button onclick="return phoneValid(this);" class="btn btn-success btn-block btn-md">Submit</button>
				</form>

	</div>
	<div class="col-sm-4"></div>

			</div>
			<div class="row">
				<div class="panel panel-warning">
                <div align="center" class="panel-heading">

					<p><b>NOTE: </b>If you are not able to submit this form It is because your browser doesn't support geoLocation</p>
				<p>You Need to try from some another Browser.</p>
                </div>

			</div>

		</div>


<style>
input[type=text],input[type=email],input[type=password],select{

    width: 290px;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 10px;
    font-size: 16px;
    background-color: white;
    background-image: url('searchicon.png');
    background-position: 10px 10px;
    background-repeat: no-repeat;
    padding: 12px 20px 12px 40px;
    -webkit-transition: width 0.4s ease-in-out;
    transition: width 0.4s ease-in-out;
       border-left:0px;
     border-right:0px;
}

input[type=text]:focus,input[type=email]:focus,input[type=password]:focus,select:focus{
width:100%;
}
</style>
<script>

var x = document.getElementById("head");
function getLocation() {

    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition,showError);
    } else {
        x.innerHTML = "Geolocation is not supported by this browser.";
    }
}

function showPosition(position) {
	 document.getElementById("id_latitude").setAttribute('value',position.coords.latitude);
  	document.getElementById("id_longitude").setAttribute('value',position.coords.longitude);


}

function showError(error) {

var x = document.getElementById("err");
    switch(error.code) {
        case error.PERMISSION_DENIED:
            x.innerHTML = "User denied the request for Geolocation."
            break;
        case error.POSITION_UNAVAILABLE:
            x.innerHTML = "Location information is unavailable."
            break;
        case error.TIMEOUT:
            x.innerHTML = "The request to get user location timed out."
            break;
        case error.UNKNOWN_ERROR:
            x.innerHTML = "An unknown error occurred."
            break;
    }
}


function phoneValid(){
var phone = document.getElementById("phone")
var pin = document.getElementById("id_pincode")

if(phone.value.length < 10){
          alert("phone number must be of 10 digits");
          phone.focus();
          return false;
    }


else if (pin.value.length <6){
   alert("pincode  must be of 6 digits long.");
          pin.focus();
          return false;

	}

else{
    return true;

}

}

$(window).load(function() {
 getLocation();
});

</script>
{%endblock%}

accounts/templates/accounts/copyright.html
{%extends 'food/base.html'%}


{%block body%}
  <div  class="container" style="margin-top:80px;">

 <h1 id="head1" align="center"><b><u>Copy Right Policy</u></b></h1>

      <div class="w3-padding-32">
              <p>Information and statements regarding products, supplements etc listed on funutritionstore have not been
            evaluated by the Food and Drug Administration or any government authority and are  not intended to diagnose,
            treat, cure, or prevent any disease. Please  read product packaging carefully prior to purchase and use. The
            results  from the products will vary from person to person. No individual result  should be seen as typical.
                  <b>Copyright © 2018 Kerni Fitness Private Limited</b> - All Rights Reserved. </p>



                   </div>
  </div>


{%endblock%}

accounts/templates/accounts/index.html
{%extends 'food/base.html'%}


{%block body%}
{%if request.user.is_authenticated%}

 		<script>
			window.location.href="/food/restaurants"
		</script>
	{% else %}
<br><br><br><br>
<div class="container-fluid">
	 {%if messages%}

        {%for message in messages%}
    <div align="center" class="alert alert-danger">
        <strong>{{message}}</strong>
    </div>
        {%endfor%}
    {%endif%}


	   {%if form.errors%}
	 <div align="center" class="alert alert-danger">
        <strong>{{ form.username.errors }}{{ form.password1.errors }}{{form.password2.errors}}</strong>
    </div>
	{%endif%}
    </div>

	<div class="row">

	<div class="col-sm-4"></div>



		<div class="well well-lg col-sm-4" style="margin-left:10px;">

			<h1 id="head" align="center"> SIGN UP</h1>

<form  class="form-horizontal" method="post" action="" enctype="multipart/form-data">
	 <div class="form-group">
	 {%csrf_token%}

		  {{form.username.label_tag}}
    		{{form.username}}
		 <br>
		  <div   class="alert alert-success">
			  <strong>{{form.username.help_text}}</strong>
		  </div>

  </div>
	 <div class="form-group">
		  {{form.email.label_tag}}
		 {{form.email}}

	 </div>
	 <div class="form-group">
		  {{form.first_name.label_tag}}
		 {{form.first_name}}

	 </div>
	 <div class="form-group">
		  {{form.last_name.label_tag}}
		 {{form.last_name}}

	 </div>
	 <div class="form-group">
		  {{form.password1.label_tag}}<br>
		  <input style="display:inline;" type="password" name="password1" required class="form-control" id="id_password1" />
		  <span  onmouseover="newPassword1()" onmouseout="newPassword1Show()" class="glyphicon glyphicon-eye-open"></span>
		 <br><br>
		 	 <div   class="alert alert-success">

				 <strong>{{ form.password1.help_text|safe }}</strong>
			 </div>


	 </div>
	 <div class="form-group">
		  {{form.password2.label_tag}}<br>
		  <input style="display:inline;" type="password" name="password2" required class="form-control" id="id_password2" />
		  <span  onmouseover="newPassword2()" onmouseout="newPassword2Show()" class="glyphicon glyphicon-eye-open"></span>
		 <br><br>
		 <div  class="alert alert-success">
			 <strong>{{form.password2.help_text}}</strong>
		 </div>

	 </div>





	<button class="btn btn-success btn-block">signup</button>
</form>
			</div>
		<div class="col-sm-4"></div>
	</div>

<style>
input[type=text],input[type=email],input[type=password]{

    width: 290px;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 10px;
    font-size: 16px;
    background-color: white;
    background-image: url('searchicon.png');
    background-position: 10px 10px;
    background-repeat: no-repeat;
    padding: 12px 20px 12px 40px;
    -webkit-transition: width 0.4s ease-in-out;
    transition: width 0.4s ease-in-out;
    border-left:0px;
     border-right:0px;
}

input[type=text]:focus,input[type=email]:focus,input[type=password]:focus{
width:90%;
}
</style>
<script>

	 function newPassword1() {
    var x = document.getElementById("id_password1");
    if (x.type === "password") {
        x.type = "text";
    } else {
        x.type = "password";
    }
}


function newPassword1Show() {
    var x = document.getElementById("id_password1");
    if (x.type === "text") {
        x.type = "password";
    } else {
        x.type = "text";
    }
}

 function newPassword2() {
    var x = document.getElementById("id_password2");
    if (x.type === "password") {
        x.type = "text";
    } else {
        x.type = "password";
    }
}



function newPassword2Show() {
    var x = document.getElementById("id_password2");
    if (x.type === "text") {
        x.type = "password";
    } else {
        x.type = "text";
    }
}



</script>
{%endif%}
{%endblock%}

accounts/templates/accounts/password_reset_complete.html
{% extends 'food/base.html'  %}
{% block title%}
     Log in
{% endblock %}


{%block body%}

<div class="container-fluid" style="margin-top:120px;">
    <div class="jumbotron">
        <h2 align="center">Congratulations, Your Password has been reset Successfully.</h2>
        <h3 align="center">You can <b><a href="{%url 'accounts:login'%}">Login </a></b>Now. </h3>


    </div>
</div>
{%endblock%}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'food/base.html'  %}
{% block title%}
     Log in
{% endblock %}

{%block body%}

{%if validlink %}



<br><br><br><br>
 <div class="container">
      {%if form.errors%}
			 <div align="center" class="alert alert-danger">
        	<strong>

						{{form.new_password1.errors}}
						{{form.new_password2.errors}}</strong>
    	</div>
		{%endif%}
	<div class="row">

	<div class="col-sm-4"></div>



		<div class="well well-lg col-sm-4"  style="margin-left:10px;">

            <h1 id="head"  align="center">Password Reset Confirm</h1>

    <form class="form-horizontal" action="." method="post" enctype="multipart/form-data">
          {% csrf_token%}
         <div class="form-group">
         {{form.new_password1.label_tag}}
             <br>
        <input type="password" style="display:inline;" class="form-control" name="new_password1" required id="id_new_password1" />
              <span  onmouseover="newPassword1()" onmouseout="newPassword1Show()" class="glyphicon glyphicon-eye-open"></span>
         </div>

        <div  class="alert alert-success">
						  <strong> <ul>
							   <li>Your password can't be too similar to your other personal information.</li>
							   <li>Your password must contain at least 8 characters.</li>
							   <li>Your password can't be a commonly used password.</li>
							   <li>Your password can't be entirely numeric.</li>
						   </ul></strong>
								 </div>

         <div class="form-group">
           {{form.new_password2.label_tag}}<br>
            <input type="password" style="display:inline;"  class="form-control" name="new_password2" required id="id_new_password2" />
              <span  onmouseover="newPassword2()" onmouseout="newPassword2Show()" class="glyphicon glyphicon-eye-open"></span>
         </div>

					   <div  class="alert alert-success">
						   <strong>Enter the same password as before, for verification.</strong>
					   </div>

         <button class="btn btn-block btn-success">Reset Password</button>
    </form>
 </div>
{%else%}


        <div class="jumbotron" style="margin-top:80px;">
    <h2 align="center">Your password Reset link is invalid</h2>
            <h3 align="center"><b>The link May be either used or Url is Incorrect.</b></h3>
            <h3 align="center">Please try Again</h3>
         </div>
            </div>
{%endif%}

    </div>


<style>
input[type=text],input[type=email],input[type=password]{

    width: 290px;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 10px;
    font-size: 16px;
    background-color: white;
    background-image: url('searchicon.png');
    background-position: 10px 10px;
    background-repeat: no-repeat;
    padding: 12px 20px 12px 40px;
    -webkit-transition: width 0.4s ease-in-out;
    transition: width 0.4s ease-in-out;
    border-left:0px;
     border-right:0px;
}

input[type=text]:focus,input[type=email]:focus,input[type=password]:focus{
width:90%;
}
</style>

<script>


 function newPassword1() {
    var x = document.getElementById("id_new_password1");
    if (x.type === "password") {
        x.type = "text";
    } else {
        x.type = "password";
    }
}


function newPassword1Show() {
    var x = document.getElementById("id_new_password1");
    if (x.type === "text") {
        x.type = "password";
    } else {
        x.type = "text";
    }
}

 function newPassword2() {
    var x = document.getElementById("id_new_password2");
    if (x.type === "password") {
        x.type = "text";
    } else {
        x.type = "password";
    }
}



function newPassword2Show() {
    var x = document.getElementById("id_new_password2");
    if (x.type === "text") {
        x.type = "password";
    } else {
        x.type = "text";
    }
}

</script>
{%endblock%}

accounts/templates/accounts/password_reset_done.html
{% extends 'food/base.html'  %}
{% block title%}
     Log in
{% endblock %}

{%block body%}
<div class="container" style="margin-top:80px;">
    <div class="jumbotron">
        <h2 align="center">You requested for Password Reset.</h2>
        <h3 align="center"><b>We have send an email containing a link for password reset form.</b> </h3>
        <h4 align="center">If you have not Received an Email ,It must be a <u>system Fault</u> or <u>Your email Address was Incorrect</u>.</h4>

    </div>


</div>



{%endblock%}

accounts/templates/accounts/password_reset_email.html
you requested for password Reset vai {{email}}
Follow the below link to Reset Your Password:
{{protocol}}://{{domain}}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

your user name:{{user.get_username}}

accounts/templates/accounts/password_reset_form.html
{% extends 'food/base.html'  %}
{% block title%}
     Log in
{% endblock %}


{% block body %}


<br><br><br><br>
 <div class="container">
	<div class="row">

	<div class="col-sm-4"></div>



		<div class="well well-lg col-sm-4"  style="margin-left:10px;">

            <h1 id="head"  align="center">Password Reset</h1>
                    <form class="form-horizontal" action="." method="post" enctype="multipart/form-data">
                        <div class="form-group">

                                    <p><label for="id_email">Email:</label> <input type="email" class="form-control" value="{{request.user.email}}" name="email" maxlength="254"  id="id_email" required /></p>
                                    <br>
                            <div  class="alert alert-success">
                                <strong>
                                    Enter Your Registered Email Address.
                                </strong>
                            </div>
                            <p><input type="submit" value="send e-mail" class="btn btn-block btn-success"></p>
                                    {% csrf_token%}

                        </div>
                    </form>
        </div>
    </div>
 </div>

<style>
input[type=email]{

    width: 290px;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 10px;
    font-size: 16px;
    background-color: white;
    background-image: url('searchicon.png');
    background-position: 10px 10px;
    background-repeat: no-repeat;
    padding: 12px 20px 12px 40px;
    -webkit-transition: width 0.4s ease-in-out;
    transition: width 0.4s ease-in-out;
    border-left:0px;
     border-right:0px;
}

 input[type=email]:focus{
width:90%;
}
    </style>
{% endblock%}