food/urls.py
from django.conf.urls import url
from . import views
from django.urls import path


app_name = 'food'

urlpatterns = [


    url(r'restaurants$', views.restaurants_list_view, name='restaurants_list'),
    url(r'restaurants/advanced$', views.advanced_search_view, name='advanced_list'),
    url(r'^restaurants/my$', views.my_restaurant_list, name='my_restaurant_list'),
    url(r'^restaurants/(?P<pk>[0-9]+)/$', views.restaurant_detail_view, name='restaurant-detail'),
    url(r'^menu/(?P<pk>[0-9]+)/add/$', views.add_to_cart,name='add-cart'),
    url(r'^cart/$', views.cart_view, name='my_cart'),
    url(r'^cart/(?P<pk>[0-9]+)/delete/$', views.delete_from_cart, name='delete-cart'),
    url(r'^order/confirm/$', views.order_confirm_view, name='order_confirm'),
    url(r'^clear/cart/$', views.clear_cart, name='delete-all-cart'),
    url(r'^contact/$', views.contact_view, name='contact'),
    url(r'^my-orders/$', views.my_orders_view, name='my_orders'),
    url(r'^my-orders/(?P<pk>[0-9]+)/$', views.my_order_deatil, name='my_orders_detail'),
    url(r'^cart/order/paypal/confirm/$', views.paypal_cnf, name='paypal_cnf'),



]

hunger/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^food/', include('food.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^ordermanage/', include('ordermanage.urls')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ordermanage/urls.py
from django.conf.urls import url
from . import views
from django.urls import path


app_name = 'ordermanage'

urlpatterns = [


    url(r'^orders/$', views.order_list_view, name='order-list'),
    url(r'orders/(?P<pk>[0-9]+)/detail/$', views.order_detail_view, name='order-detail'),
    url(r'orders/(?P<pk>[0-9]+)/confirm/$',views.order_list_update_view, name='order-list-update'),
    url(r'confirm-orders/$', views.confirm_orders, name='order-confirm-list'),
    url(r'confirm-orders/(?P<pk>[0-9]+)/$', views.confirm_order_detail, name='confirm-order'),
    url(r'restaurants/orders/$', views.resturants_orders, name='order'),






]

ordermanage/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from food.models import Menu,CartManager


class OrdersDone(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None, blank=True, null=True)
    item = models.ForeignKey(Menu, on_delete=models.CASCADE, null=True)
    cartmanager = models.ForeignKey(CartManager, on_delete=models.CASCADE, null=True)
    add_time = models.DateTimeField(auto_now=True)
    item_price = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    etc_price = models.DecimalField(max_digits=6, decimal_places=2, default=0)

    def __str__(self):
        return str(self.item)


class OrderManager(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None, blank=True, null=True)
    delivery_time = models.DateTimeField(auto_now_add=True)
    order_id = models.CharField(max_length=10, default=0)
    payment = models.CharField(max_length=20,  )
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    sub_total = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    status = models.BooleanField(default=False)
    etc_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return str(self.order_id)


class OrdersConfirm(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None, blank=True, null=True)
    item = models.ForeignKey(Menu, on_delete=models.CASCADE, null=True)
    cartmanager = models.ForeignKey(OrderManager, on_delete=models.CASCADE, null=True)
    add_time = models.DateTimeField(auto_now=True)
    item_price = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    etc_price = models.DecimalField(max_digits=6, decimal_places=2, default=0)

    def __str__(self):
        return str(self.item)

ordermanage/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect,get_object_or_404
from food.models import CartManager
from django.contrib.auth.decorators import login_required
from ordermanage.models import OrdersDone,OrdersConfirm,OrderManager
from django.http import HttpResponse,JsonResponse
from django.contrib import messages
from datetime import date
from twilio.rest import Client


@login_required
def order_list_view(request):
    if request.user.is_superuser or request.user.is_staff:

        queryset = CartManager.objects.all().order_by("-order_time")
        return render(request, 'ordermanage/orders.html', {'orders_list': queryset})

    else:
        return redirect('/food/restaurants')


@login_required
def order_detail_view(request,pk):
    if request.user.is_superuser or request.user.is_staff:
        order = get_object_or_404(CartManager, pk=pk)
        return render(request, 'ordermanage/order_detail.html', {'order': order})

    else:
        return redirect('/food/restaurants')

@login_required
def order_list_update_view(request,pk):
    order = get_object_or_404(CartManager,pk=pk)
    if request.method =="POST":
        if request.user.is_superuser or request.user.is_staff:

            status = request.POST['status']
            order_manager = OrderManager()
            order_manager.user = order.user
            order_manager.order_id = order.order_id
            order_manager.payment = order.payment
            order_manager.sub_total = order.sub_total
            order_manager.total = order.total
            order_manager.etc_price = order.etc_price

            account_sid = "ACfcdc76a71768bba5a8fa1695dece27c9"
            auth_token = "f6683c048cee22a89dcf20e4009caca8"

            client = Client(account_sid, auth_token)
            number = order_manager.user.profile.phone
            num = "+91" + number
            if status == "true":
                order_manager.status = True
                order_manager.save()
                #client.api.account.messages.create(to=num, from_="+18305005658",
                                                   #body="Hello your order is successfully delivered")
            elif status == "false":
                order_manager.status = False
                order_manager.save()
                #client.api.account.messages.create(to=num, from_="+18305005658",
                                                   #body="Hello your order is un-successfully delivered")

            for orders in OrdersDone.objects.filter(cartmanager=order):
                order_cnf = OrdersConfirm()
                order_cnf.user = orders.user
                order_cnf.item = orders.item
                order_cnf.etc_price = orders.etc_price
                order_cnf.item_price = orders.item_price
                order_cnf.cartmanager = order_manager
                order_cnf.save()

            order.delete()
            return redirect('/ordermanage/orders/')
        else:
            return redirect('/food/restaurants')
    else:
        return redirect('/ordermanage/orders/')

@login_required
def confirm_orders(request):
    if not request.user.is_superuser:
        return redirect('/food/restaurants')
    else:
        queryset = OrderManager.objects.all().order_by("-delivery_time")
        return render(request, 'ordermanage/confirm_orders.html', {'orders_list': queryset})


@login_required
def confirm_order_detail(request,pk):
    if not request.user.is_superuser:
        return redirect('/food/restaurants')
    else:
        order = get_object_or_404(OrderManager, pk=pk)
        return render(request, 'ordermanage/confirm_order_detail.html', {'cnf_order':order})


@login_required
def resturants_orders(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            restaurant = request.POST['restaurant'].strip()
            month = request.POST['month']
            year = request.POST['year']
            list = OrdersConfirm.objects.filter(add_time__month=month, add_time__year=year)
            context = {
                'list': list,
                'rest_name':restaurant,

            }
            return render(request,'food/rest_pay_post.html', context)
        else:

            list = OrdersConfirm.objects.all()
            return render(request, 'ordermanage/restaurants_pay.html', {'list': list})

    else:
        return redirect('/food/restaurants')

ordermanage/templates/ordermanage/confirm_order_detail.html
{%extends 'food/base.html'%}
{%block body%}


<div class="container" style="margin-top:100px;">

    <div class="row">
        <div class="col-sm-8" id="order-list-body">
    {%if messages%}

        {%for message in messages%}
    <div align="center" class="alert alert-danger">
        <strong>{{message}}</strong>
    </div>
        {%endfor%}
    {%endif%}

           <h2 align="center"><b id="head">Order Number:&nbsp;</b>{{cnf_order.order_id}}</h2>

            <br><br>

            <div>
             <table class="table table-stripe" id="myTable" style="width:100%;">
                 <thead>
                 <tr>
                     <th>S.No.</th>
                       <th>Item</th>
                        <th>Ordered From</th>
                        <th>Amount</th>
                     <th></th>
                 </tr>
                    </thead>
                 <tbody>




                  <script>
                var i=0;
                var j;
                var cost = new Array({{cart_count}});
                var adder = 0;
                </script>

            {%for cart in cnf_order.ordersconfirm_set.all%}

            <script>
               cost[i] = {{cart.etc_price}}
               i++;
               </script>
            {%endfor%}

            <script>
          var noDupe = Array.from(new Set(cost))
          var l = noDupe.length;
          for(j=0;j<l;j++){
          adder = adder+noDupe[j];
            }
 </script>

                 <script>
                     var count = 0;
                 </script>
            {%for order in cnf_order.ordersconfirm_set.all%}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{order.item.name}}</td>
                <td>{{order.item.restaurant}}</td>
                <td>{{order.item.price}}</td>
            </tr>
                    <script>
                        var item = {{order.item.price}};
                        count = count+item;

                    </script>


              {%endfor%}
                 <tr>
                     <td></td>
                       <td></td>
                       <td></td>
                       <td><b>Total:</b>&nbsp;<span class="fa fa-inr"></span><script>
                        document.write(count);

                        </script><br>
                       <b>Etc Charges:</b>&nbsp;<span class="fa fa-inr"></span><script>
                        document.write(adder);

                        </script><br>
                       <b>Sub Total:</b>&nbsp;<span class="fa fa-inr"></span><script>
                        document.write(count+adder);

                        </script></td>

                 </tr>
                 </tbody>
             </table>
                    <div class="row">
                        <div class="col-sm-5">
                            {%if cnf_order.status%}
                            <h3 style="display:inline;"><b>Status:&nbsp;</b><span style="color:rgb(64, 178, 76);" class="glyphicon glyphicon-ok-sign">&nbsp;Delivered</span> </h3>
                            {%else%}
                             <h3 style="display:inline;"><b>Status:&nbsp;</b><span style="color:rgb(255, 99, 71);" class="glyphicon glyphicon-remove-sign">&nbsp;NotDelivered</span></h3>

                            {%endif%}

                        </div>
                        <div class="col-sm-1"></div>
                        <div class="col-sm-5">
                <form id="status_form{{order.id}}" method="get" action="/ordermanage/confirm-orders/">
                {%csrf_token%}

                 <button class="btn btn-md btn-danger btn-block"><span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Back</button>

            </form>
                            </div>
            </div>


            </div>
        </div>
        <div class="col-sm-1"></div>
        <div class="col-sm-4">
                      <br><br>


                <br><br>




            <div class="panel panel-default">
                <div class="panel-heading"><h3>Delivery Address</h3></div>
            <div class="panel-body">
                <table>
                    <tbody>
                      <tr>
                        <td><b>Name:&nbsp;</b>{{cnf_order.user.first_name}}&nbsp;{{cnf_order.user.last_name}}</td>

                    </tr>
                    <tr>
                        <td><b>Address&nbsp;</b>{{cnf_order.user.profile.address}}</td>

                    </tr>
                    <tr>
                        <td><b>Contact No.: &nbsp;</b>{{cnf_order.user.profile.phone}}</td>

                    </tr>
                     <tr>
                        <td><b>Pincode:&nbsp;</b>{{cnf_order.user.profile.pincode}}</td>

                    </tr>
                     <tr>
                        <td><b>Landmark:&nbsp;</b>{{cnf_order.user.profile.land_mark}}</td>

                    </tr>
                     <tr>
                        <td><b>Payment:&nbsp;</b>{{cnf_order.payment}}</td>

                    </tr>
                    </tbody>
                </table>



            </div>
          </div>

        </div>
    </div>
</div>

<script>


    var btn = $("#Button");
btn.prop("disabled", true);
</script>
{%endblock%}

ordermanage/templates/ordermanage/confirm_orders.html
{%extends 'food/base.html'%}
{%block body%}


<div class="container" style="margin-top:100px;">
    <div class="row">
        <div class="col-sm-12">
    {%if messages%}

        {%for message in messages%}
    <div align="center" class="alert alert-danger">
        <strong>{{message}}</strong>
    </div>
        {%endfor%}
    {%endif%}<br>
            <h2 id="head" align="center"><b><u>Confirmed/Not Confirmed Orders</u></b></h2><br>

            <div class="row">
            <div class="col-sm-10">
            <input style="width:100%;" class="form-control" id="myInput" type="text" placeholder="Search.... Users, Order id, Restaurant, Etc...">
                </div>
                  <div class="col-sm-2">
            &nbsp; &nbsp;   <form  method="get" action="{%url 'ordermanage:order-list'%}">
                {%csrf_token%}
                 <button style="margin-top:-20px;" class="btn btn-md btn-info btn-block"><span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Back</button>
            </form>


                  </div>
            </div>


                <br><br><br>
            <div>
                <table class="table table-stripe" id="myTable" style="width:100%;">
                 <thead>
                 <tr>
                     <th>S.No.</th>

                       <th>Ordered By</th>

                          <th>Order Id</th>
                        <th>Order Time</th>
                        <th>Amount</th>
                     <th>Status</th>
                     <th>Action</th>

                 </tr>
                    </thead>

        <tbody id="order_list">
    {%for cnf_order in orders_list%}
        <tr id="orders">

            <td>{{forloop.counter}}</td>
             <td>{{cnf_order.user.first_name}}&nbsp;{{cnf_order.user.last_name}}</td>

             <td>{{cnf_order.order_id}}</td>
            <td>{{cnf_order.delivery_time }}</td>
             <td>{{cnf_order.sub_total}}</td>

            <td>
                {%if cnf_order.status %}



                <h3 style="color:rgb(64, 178, 76);display:inline;"><span class="glyphicon glyphicon-ok-circle"></span></h3>

                {%else%}

                <h3 style="color:rgb(255, 99, 71);display:inline;"><span class="glyphicon glyphicon-remove-circle"></span>  </h3>


                {%endif%}


            </td>
             <td><form id="status_form{{order.id}}" method="get" action="/ordermanage/confirm-orders/{{cnf_order.id}}">
                {%csrf_token%}

                 <button class="btn btn-md btn-primary btn-block"><span class="glyphicon glyphicon-share"></span>&nbsp;View</button>

            </form></td>


        </tr>
            {%endfor%}
        </tbody>

               </table>


</div>






        </div>
    </div>
</div>
        <br />
<script>


    $(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});




function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});




</script>
{%endblock%}

ordermanage/templates/ordermanage/order_detail.html
{%extends 'food/base.html'%}
{%block body%}


<div class="container" style="margin-top:100px;">

    <div class="row">
        <div class="col-sm-8" id="order-list-body">
    {%if messages%}

        {%for message in messages%}
    <div align="center" class="alert alert-danger">
        <strong>{{message}}</strong>
    </div>
        {%endfor%}
    {%endif%}
           <h2 align="center"><b id="head">Order Number:</b>{{order.order_id}}</h2><br><br>

             <table class="table table-stripe" id="myTable" style="width:100%;">
                 <thead>
                 <tr>
                     <th>S.No.</th>
                       <th>Item</th>
                        <th>Ordered From</th>
                        <th>Amount</th>
                     <th></th>
                 </tr>
                    </thead>
                 <tbody>



                  <script>
                var i=0;
                var j;
                var cost = new Array({{cart_count}});
                var adder = 0;
                </script>

            {%for cart in order.ordersdone_set.all%}

            <script>
               cost[i] = {{cart.etc_price}}
               i++;
               </script>
            {%endfor%}

            <script>
          var noDupe = Array.from(new Set(cost))
          var l = noDupe.length;
          for(j=0;j<l;j++){
          adder = adder+noDupe[j];
            }
 </script>

                 <script>
                     var count = 0;
                 </script>
            {%for order in order.ordersdone_set.all%}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{order.item.name}}</td>
                <td>{{order.item.restaurant}}</td>
                <td>{{order.item.price}}</td>
            </tr>
                    <script>
                        var item = {{order.item.price}};
                        count = count+item;

                    </script>


              {%endfor%}
                    </tbody>
             </table>


                        <b>Total:&nbsp;<span class="fa fa-inr"></span></b><script>
                        document.write(count);


                        </script><br>


                         <b>Etc Charges:&nbsp;<span class="fa fa-inr"></span></b><script>
                        document.write(adder);


                        </script><br>
                       <b>Sub Total:&nbsp;<span class="fa fa-inr"></span></b><script>
                        document.write(count+adder);


                        </script>


            <div class="row">
                <div class="col-sm-5">
            <form action="/ordermanage/orders/{{order.id}}/confirm/" method="post">
                {%csrf_token%}
                <input type="hidden" name="status" value="true">
            <button class="btn btn-block btn-info" value="Confirm">Confirm</button>
                </form>
                </div>
                 <div class="col-sm-5">
                   <form action="/ordermanage/orders/{{order.id}}/confirm/" method="post">
                {%csrf_token%}
                           <input type="hidden" name="status" value="false">
            <button class="btn btn-block btn-danger" value="Confirm">Cancel</button>
                </form>
                 </div>
                </div>
        </div>
        <div class="col-sm-1"></div>
        <div class="col-sm-4">
            <br><br><br><br>
            <div class="panel panel-default">
                <div class="panel-heading"><h3>Delivery Address</h3></div>
            <div class="panel-body">
                <table>
                    <tbody>
                      <tr>
                        <td><b>Name:&nbsp;</b>{{order.user.first_name}}&nbsp;{{order.user.last_name}}</td>

                    </tr>
                    <tr>
                        <td><b>Address&nbsp;</b>{{order.user.profile.address}}</td>

                    </tr>
                    <tr>
                        <td><b>Contact No.: &nbsp;</b>{{order.user.profile.phone}}</td>

                    </tr>
                     <tr>
                        <td><b>Pincode:&nbsp;</b>{{order.user.profile.pincode}}</td>

                    </tr>
                     <tr>
                        <td><b>Landmark:&nbsp;</b>{{order.user.profile.land_mark}}</td>

                    </tr>
                     <tr>
                        <td><b>Payment:&nbsp;</b>{{order.payment}}</td>

                    </tr>
                    </tbody>
                </table>
            </div>
            </div>
            </div>

          </div>

        </div>
<br><br><br><br>
{%endblock%}

ordermanage/templates/ordermanage/orders.html
{%extends 'food/base.html'%}
{%block body%}


<div class="container" style="margin-top:70px;">
      {%if orders_list%}
    <div class="row">
        <div class="col-sm-12" id="order-list-body">
    {%if messages%}

        {%for message in messages%}
    <div align="center" class="alert alert-danger">
        <strong>{{message}}</strong>
    </div>
        {%endfor%}
    {%endif%}
           <h2 id="head" align="center"><b>Arrived Orders</b></h2><br>

            <div class="row">
                <div class="col-sm-10">
            <input  style="width:100%;" class="form-control" id="myInput" type="text" placeholder="Search.... Users, Order id, Restaurant, Etc...">&nbsp;&nbsp;&nbsp;&nbsp;
               </div> <div class="col-sm-2"> <a href="{%url 'ordermanage:order-confirm-list'%}"   class="btn btn-info btn-block btn-md">
          <span class="glyphicon glyphicon-ok-circle"></span> Confirmed Orders
        </a></div>
                </div><br><br>

            <div id="order-body">
               <table class="table table-stripe" id="myTable" style="width:100%;">
                 <thead>
                 <tr>
                     <th>S.No.</th>

                       <th>Ordered By</th>

                          <th>Order Id</th>
                        <th>Order Time</th>
                        <th>Amount</th>
                     <th></th>
                 </tr>
                    </thead>

        <tbody id="order_list">
    {%for order in orders_list%}
        <tr id="orders">

            <td>{{forloop.counter}}</td>
             <td>{{order.user.first_name}}&nbsp;{{order.user.last_name}}</td>

             <td><a href="/ordermanage/orders/{{order.id}}/detail"> {{order.order_id}}</a></td>
            <td>{{order.order_time }}</td>
             <td>{{order.sub_total}}</td>
            <td><form id="status_form{{order.id}}" method="get" action="/ordermanage/orders/{{order.id}}/detail">
                {%csrf_token%}

                 <button class="btn btn-md btn-primary btn-block"><span class="glyphicon glyphicon-check"> </span>&nbsp;View</button>

            </form></td>


        </tr>
            {%endfor%}
        </tbody>

               </table>
            </div>

        </div>
    </div>
    {%else%}
    <div class="row">
        <div class=" jumbotron col-sm-12">
                   <h2 align="center">No New Orders Yet</h2>
            <br><br>
            <div align="center">
             <a  href="{%url 'ordermanage:order-confirm-list'%}" style="display:inline" class="btn btn-info btn-block btn-lg">
          <span class="glyphicon glyphicon-chevron-right"></span>Go To Confirmed Orders
        </a></div>



        </div>



    </div>
    {%endif%}

</div>

<style>



</style>



<script>




    $(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});




function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});




</script>
<br><br>
{%endblock%}

ordermanage/templates/ordermanage/restaurants_pay.html
{%extends 'food/base.html'%}
{%block body%}


<div class="container" style="margin-top:100px;">
      {%if list%}
    <div class="row">
        <div class="col-sm-12" id="order-list-body">
     <h2 align="center" id="head"><b>All Restaurants </b></h2><br>

              <div class="row">

                    <form class="form-inline" action="/ordermanage/restaurants/orders/" method="post" >
                       {%csrf_token%}
                       <div class="col-sm-5 form-group">
                           <label>Restaurant Name:</label>
            <input style="width:100%;"  name="restaurant" class="form-control" id="myInput" type="text" required  >
                       </div>
                       <div class=" col-sm-3 form-group">
                           <label>Select Month:</label>
                  <select name="month" class="form-control" style="width:100%;"  >
                     <option value="1">January</option>
                        <option value="2">February</option>
                        <option value="3">March</option>
                        <option value="4">April</option>
                        <option value="5">May</option>
                        <option value="6">June</option>
                        <option value="7">July</option>
                        <option value="8">August</option>
                        <option value="9">September</option>
                        <option value="10">October</option>
                        <option value="11">November</option>
                        <option value="12">December</option>
            </select>
                       </div>
                       <div class=" col-sm-3 form-group" >
                           <label >Select Year:</label>
                         <select name="year" class="form-control" style="width:100%;">
                        <option value="2018">2018</option>
                        <option value="2019">2019</option>
                        <option value="2020">2020</option>
                             <option value="2021">2021</option>
                             <option value="2022">2022</option>
                             <option value="2023">2023</option>
                             <option value="2024">2024</option>
            </select>
                       </div>
                         <div class=" col-sm-1" >
                             <label>&nbsp;</label>
                       <button  class="btn btn-info btn-md btn-block">Go</button>
                         </div>
                </form>
                 </div><br>

            <div id="order-body">

                <script>

                   var count=0;
                </script>

               <table class="table table-stripe" id="myTable" style="width:100%;">
                 <thead>
                 <tr>
                     <th>S.No.</th>

                       <th>Ordered By</th>
                     <th>Ordered From</th>
                          <th>Order Id</th>
                     <th>Item</th>
                        <th>Order Time</th>
                        <th>Amount</th>

                 </tr>
                    </thead>

        <tbody id="order_list">

    {%for order in list%}
        <tr id="orders">


            <td>{{forloop.counter}}</td>
             <td>{{order.cartmanager.user.first_name}}&nbsp;{{order.cartmanager.user.last_name}}</td>
                 <td> {{order.item.restaurant.name}}</td>
                <td>{{order.cartmanager.order_id}}</td>
             <td>{{order.item.name}}</td>
            <td>{{order.cartmanager.delivery_time }}</td>
             <td class="price">{{order.item.price}}</td>

        </tr>
            {%endfor%}
        </tbody>

               </table>

            </div>

        </div>
    </div>
    {%else%}
    <div class="row">
        <div class=" jumbotron col-sm-12">
                   <h2 align="center">No Orders yet</h2>




        </div>



    </div>
    {%endif%}

</div>

<style>



</style>

<script>




    $(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});







</script>
<br><br>
{%endblock%}